# Generated by Django 6.1 on 2026-09-01 12:12

import apps.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the birthday person', max_length=150)),
                ('nickname', models.CharField(blank=True, help_text='Sweet nickname or preferred name', max_length=100)),
                ('slug', models.SlugField(help_text="Unique URL path slug (e.g., 'priya' for /priya/)", max_length=100, unique=True, validators=[apps.profiles.models.validate_reserved_slug])),
                ('birthday_date', models.DateField(help_text='The birthday date')),
                ('relationship_start_date', models.DateField(blank=True, help_text='Date relationship started', null=True)),
                ('first_meeting_date', models.DateField(blank=True, help_text='Date of first meeting', null=True)),
                ('profile_image', models.ImageField(blank=True, help_text='Main profile picture', null=True, upload_to='profiles/profile_images/')),
                ('hero_image', models.ImageField(blank=True, help_text='Hero section backdrop image', null=True, upload_to='profiles/hero_images/')),
                ('cover_image', models.ImageField(blank=True, help_text='Cover banner image', null=True, upload_to='profiles/cover_images/')),
                ('intro_message', models.TextField(blank=True, help_text='Landing intro text')),
                ('final_message', models.TextField(blank=True, help_text='Closing birthday message')),
                ('special_letter', models.TextField(blank=True, help_text='Private or special letter message')),
                ('is_active', models.BooleanField(default=True, help_text='Master active toggle for the profile')),
                ('publish_date', models.DateTimeField(blank=True, help_text='Schedule profile to go live at a specific date/time (optional)', null=True)),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Optional expiration date/time', null=True)),
                ('expiry_behavior', models.CharField(choices=[('keep_public', 'Keep Public (Accessible after expiry)'), ('make_private', 'Make Private (Restricted after expiry)')], default='keep_public', help_text='Action to take when expiry date is reached', max_length=20)),
                ('enable_animations', models.BooleanField(default=True, help_text='Enable floating hearts, confetti, and visual animations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Birthday Profile',
                'verbose_name_plural': 'Birthday Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
