# Generated by Django 6.1 on 2026-09-01 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdayprofile',
            name='theme',
            field=models.ForeignKey(blank=True, help_text='Visual theme for this birthday profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='themes.theme'),
        ),
    ]
