# Generated by Django 6.1 on 2026-09-03 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_birthdayprofile_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdayprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this birthday profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birthday_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
