# Generated by Django 6.1 on 2026-09-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_birthdayprofile_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdayprofile',
            name='access_password_hash',
            field=models.CharField(blank=True, help_text='Hashed version of the auto-derived access password (firstname+birth_year)', max_length=255),
        ),
        migrations.AddField(
            model_name='birthdayprofile',
            name='is_password_protected',
            field=models.BooleanField(default=True, help_text='If True, recipients must enter the access password to view the birthday page'),
        ),
    ]
