# Generated by Django 6.1.1 on 2026-09-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_access_password_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdayprofile',
            name='birth_place',
            field=models.CharField(blank=True, help_text='Optional city or place shown on the countdown page', max_length=150),
        ),
        migrations.AlterField(
            model_name='birthdayprofile',
            name='access_password_hash',
            field=models.CharField(blank=True, help_text='Hashed unique access password shown once to the creator after publish', max_length=255),
        ),
    ]
