# Generated by Django 6.1 on 2026-09-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_birthdayprofile_birth_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdayprofile',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Whether the creation payment has been verified'),
        ),
        migrations.AddField(
            model_name='birthdayprofile',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='birthdayprofile',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
