# Generated by Django 6.1 on 2026-09-01 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_birthdayprofile_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoveNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title or theme of the note (e.g., 'Your Radiant Smile')", max_length=200)),
                ('message', models.TextField(help_text='Personal love note or sweet message')),
                ('icon', models.CharField(blank=True, default='❤️', help_text='Emoji or icon identifier (e.g. ❤️, 💖, 🌟, 🌺)', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birthday_profile', models.ForeignKey(help_text='The birthday profile this love note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='love_notes', to='profiles.birthdayprofile')),
            ],
            options={
                'verbose_name': 'Love Note',
                'verbose_name_plural': 'Love Notes',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
