# Generated by Django 6.1 on 2026-09-01 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_birthdayprofile_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(help_text="Name of sender e.g., 'Mom & Dad', 'Bestie Rahul'", max_length=200)),
                ('relationship', models.CharField(blank=True, help_text="e.g. 'Parents', 'College Friend'", max_length=100)),
                ('video_file', models.FileField(blank=True, help_text='Direct video file upload (MP4, WebM)', null=True, upload_to='videos/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo, or direct video stream URL')),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional video thumbnail cover image', null=True, upload_to='videos/thumbnails/')),
                ('message_text', models.TextField(blank=True, help_text='Optional text caption accompanying video')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birthday_profile', models.ForeignKey(help_text='The birthday profile this video message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='video_messages', to='profiles.birthdayprofile')),
            ],
            options={
                'verbose_name': 'Video Message',
                'verbose_name_plural': 'Video Messages',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
