# Generated by Django 6.1 on 2026-09-01 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_birthdayprofile_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Song or playlist track title', max_length=200)),
                ('artist', models.CharField(blank=True, help_text='Artist or composer name', max_length=200)),
                ('audio_file', models.FileField(blank=True, help_text='Audio file upload (MP3, WAV, OGG, AAC)', null=True, upload_to='music/audio/')),
                ('external_url', models.URLField(blank=True, help_text='Direct stream URL if not uploading a file')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary background track for auto-play across journey steps')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birthday_profile', models.ForeignKey(help_text='The birthday profile this background music belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='music_tracks', to='profiles.birthdayprofile')),
            ],
            options={
                'verbose_name': 'Background Music Track',
                'verbose_name_plural': 'Background Music Tracks',
                'ordering': ['-is_primary', 'display_order', '-created_at'],
            },
        ),
    ]
