# Generated by Django 6.1 on 2026-09-01 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_birthdayprofile_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='A Special Secret Message 🔒', help_text='Title or envelope heading for the secret message', max_length=200)),
                ('secret_text', models.TextField(help_text='The confidential, heartfelt secret message text')),
                ('pin_code', models.CharField(blank=True, help_text="Optional passcode PIN required to unlock this secret (e.g. '1234', '0415')", max_length=10, null=True)),
                ('hint', models.CharField(blank=True, help_text="Optional hint to remind the recipient of the PIN (e.g. 'Our anniversary date')", max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Optional secret photo or surprise image', null=True, upload_to='secret/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birthday_profile', models.OneToOneField(help_text='The birthday profile this secret message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='secret_message', to='profiles.birthdayprofile')),
            ],
            options={
                'verbose_name': 'Secret Message',
                'verbose_name_plural': 'Secret Messages',
            },
        ),
    ]
