# Generated by Django 6.1 on 2026-09-01 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_birthdayprofile_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or caption for the memory', max_length=200)),
                ('description', models.TextField(help_text='Detailed story or recollection')),
                ('memory_date', models.DateField(blank=True, help_text='Date this memory took place', null=True)),
                ('image', models.ImageField(blank=True, help_text='Photo associated with this memory', null=True, upload_to='memories/images/')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which memory is displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birthday_profile', models.ForeignKey(help_text='The birthday profile this memory belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='profiles.birthdayprofile')),
            ],
            options={
                'verbose_name': 'Memory',
                'verbose_name_plural': 'Memories',
                'ordering': ['display_order', 'memory_date', '-created_at'],
            },
        ),
    ]
