# Generated by Django 6.1 on 2026-09-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Theme display name', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='Unique theme identifier', max_length=100, unique=True)),
                ('primary_color', models.CharField(default='#f43f5e', help_text='Primary brand/accent color', max_length=30)),
                ('secondary_color', models.CharField(default='#f59e0b', help_text='Secondary highlight color', max_length=30)),
                ('background_color', models.CharField(default='#020617', help_text='Page background color', max_length=30)),
                ('text_color', models.CharField(default='#f8fafc', help_text='Primary text color', max_length=30)),
                ('accent_color', models.CharField(default='#fb7185', help_text='Accent color', max_length=30)),
                ('card_bg', models.CharField(default='rgba(255, 255, 255, 0.05)', help_text='Glassmorphic card background', max_length=50)),
                ('card_border', models.CharField(default='rgba(255, 255, 255, 0.1)', help_text='Glassmorphic card border', max_length=50)),
                ('is_default', models.BooleanField(default=False, help_text='Set as platform default theme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
                'ordering': ['name'],
            },
        ),
    ]
