# Generated by Django 6.1 on 2026-09-01 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_birthdayprofile_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional photo title', max_length=200)),
                ('caption', models.TextField(blank=True, help_text='Optional caption or memory story behind the photo')),
                ('image', models.ImageField(help_text='Gallery photo image', upload_to='gallery/images/')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birthday_profile', models.ForeignKey(help_text='The birthday profile this gallery photo belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='profiles.birthdayprofile')),
            ],
            options={
                'verbose_name': 'Gallery Photo',
                'verbose_name_plural': 'Gallery Photos',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
