# Generated by Django 6.1 on 2026-09-01 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_birthdayprofile_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event title', max_length=200)),
                ('description', models.TextField(help_text='Story or details about this milestone')),
                ('event_date', models.DateField(help_text='Date this event took place')),
                ('image', models.ImageField(blank=True, help_text='Photo associated with this timeline event', null=True, upload_to='timeline/images/')),
                ('icon', models.CharField(blank=True, default='✨', help_text='Emoji or icon identifier (e.g. 💍, ✈️, ☕, 🎂)', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Secondary sort order if multiple events occur on the same date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birthday_profile', models.ForeignKey(help_text='The birthday profile this timeline event belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='profiles.birthdayprofile')),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'ordering': ['event_date', 'display_order', '-created_at'],
            },
        ),
    ]
