# Generated by Django 6.1 on 2026-09-01 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_birthdayprofile_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(help_text='Name of the person submitting the birthday wish', max_length=200)),
                ('message', models.TextField(help_text='Warm birthday wish message')),
                ('candle_blown', models.BooleanField(default=False, help_text='Whether candle blow animation was triggered')),
                ('is_approved', models.BooleanField(default=True, help_text='Approval status for public wall')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birthday_profile', models.ForeignKey(help_text='The birthday profile this wish belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='profiles.birthdayprofile')),
            ],
            options={
                'verbose_name': 'Wish Submission',
                'verbose_name_plural': 'Wish Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
